"""empty message

Revision ID: 6c0324adca5a
Revises: 
Create Date: 2024-02-15 13:46:08.988590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0324adca5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizzas',
    sa.Column('piz_id', sa.Integer(), nullable=False),
    sa.Column('piz_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('piz_id'),
    sa.UniqueConstraint('piz_name')
    )
    op.create_table('restaurants',
    sa.Column('res_id', sa.Integer(), nullable=False),
    sa.Column('res_name', sa.String(length=255), nullable=True),
    sa.Column('res_address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('res_id'),
    sa.UniqueConstraint('res_name')
    )
    op.create_table('respizza',
    sa.Column('respizza_id', sa.Integer(), nullable=False),
    sa.Column('respizza_price', sa.Integer(), nullable=True),
    sa.Column('pizzas_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pizzas_id'], ['pizzas.piz_id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.res_id'], ),
    sa.PrimaryKeyConstraint('respizza_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respizza')
    op.drop_table('restaurants')
    op.drop_table('pizzas')
    # ### end Alembic commands ###
